### ISSUE TITLE
Cache functions returning `None`

### ISSUE THREAD

**Issue by argaen** [aio-libs/aiocache#452]
Right now if you decorate a function that doesn't return anything, it will not work and will execute always, this is not intuitive

Is there a use case for this? could someone want to cache a function that doesn't return anything? happy to hear thoughts from people.

**Comment by millilux** [comment]
Hi there,

One use case where this could be useful is caching responses from a GraphQL server. We have a Sanic app that calls out to a GraphQL server. When a particular object can't be found, the GraphQL server returns a null, translating to None in Python land. 
We want to cache this result for a short duration, as we know the object will eventually become available. Currently we have some wrapper logic to handle caching a None, but it'd be nice to have the option to toggle this behaviour.

**Comment by argaen** [comment]
Yep, I also thought on cases where calling a function triggers an expensive calculation and you don't want to trigger it if the endpoint is called after 5s or something like that. But not sure how common is that. But yes makes sense.

you think this wrapper logic is something that could be reused?

**Comment by paulo-raca** [comment]
+1, same issue here.

I think we could use a guard value internally (`Cache.MISSING = object()`), and add a `default` argument on the public methods

**Comment by Dreamsorcerer** [comment]
In #652 we are looking to add a function to customise the behaviour needed to skip the cache.

So, we should proceed with caching all results, then the old behaviour can be reproduced with `skip_cache_func=lambda r: r is None`.

**Comment by antont** [comment]
Dogpile caching lib has a `NO_VALUE` thing for this purpose, to allow caching `None` as a return value.

> get(key, expiration_time=None, ignore_expiration=False)
Return a value from the cache, based on the given key.

>If the value is not present, the method returns the token NO_VALUE. NO_VALUE evaluates to False, but is separate from None to distinguish between a cached value of None.

https://dogpilecache.sqlalchemy.org/en/latest/api.html#dogpile.cache.region.CacheRegion.get

**Comment by Dreamsorcerer** [comment]
We've added the `skip_cache_func`, so this works now. Having some other sentinel value is less Pythonic and not going to work with decorators (we have to return the value the function returns...), which is probably the main use case for this library.

**Comment by kkom** [comment]
Hey @Dreamsorcerer – I think that the caching of functions returning `None` still doesn't work (despite adding `skip_cache_func` in #652).

E.g. see this example which uses `aiocache = "0.12.2"`:

```python
import asyncio
from aiocache import cached

@cached()
async def cached_returns_int() -> int:
    print("executing cached_returns_int")
    return 1

@cached()
async def cached_returns_none() -> None:
    print("executing cached_returns_none")
    return

async def test_caching() -> None:
    for _ in range(5):
        await cached_returns_int()

    for _ in range(5):
        await cached_returns_none()

asyncio.run(test_caching())
```

This prints:

```
executing cached_returns_int
executing cached_returns_none
executing cached_returns_none
executing cached_returns_none
executing cached_returns_none
executing cached_returns_none
```

I believe that's because receiving a cached value of `None` is still conflated with "the value is missing from cache" and results in running `L118`, i.e. executing the underlying function:

https://github.com/aio-libs/aiocache/blob/287711974cf5a9708883c3f0ecefad889f731961/aiocache/decorators.py#L113-L118

https://github.com/aio-libs/aiocache/blob/287711974cf5a9708883c3f0ecefad889f731961/aiocache/decorators.py#L147-L152

**Comment by Dreamsorcerer** [comment]
Hmm, yeah. If you can create a test in a PR that'd be really helpful.
