### ISSUE TITLE
Enh: Support orjson serializer

### ISSUE THREAD

**Issue by rspadim** [aio-libs/aiocache#499]

**Comment by argaen** [comment]
Hey @rspadim, it shouldn't be hard to add orjson as a supported library to use in the json serializer. Feel free (or anyone else) to provide a PR for it! :)

**Comment by Dreamsorcerer** [comment]
I think we should avoid adding too many custom serialisers and such in the project.

Instead, I'd suggest someone create a custom class elsewhere. We can link to it from the README or somewhere, so others can easily find it.
