### ISSUE TITLE
Await pending future

### ISSUE THREAD

**Issue by cancan101** [aio-libs/aiocache#516]
I am using the `SimpleMemoryCache` backend for unit tests and it does not seem like access to the cache awaits pending future like this library does: https://github.com/aio-libs/async-lru/blob/ae252508f9c5aecf9c02ddeb879d06c28dbffc42/async_lru.py#L150

This means that when I try to call my function multiple times (I am using the decorator) subsequent runs are not awaiting the prior future.

**Comment by JeppeKlitgaard** [comment]
I believe the `cached_stampede` decorator does this for you, whereas the general `cached` decorator does not.

**Comment by argaen** [comment]
As @JeppeKlitgaard mentions you either use cached_stampede or directly some of the lock implementations you can have in locks.py
