### ISSUE TITLE
CLA integration

### ISSUE THREAD

**Issue by argaen** [aio-libs/aiocache#522]
@asvetlov how could we fix this repo not having the CLA agreement? I see in PRs the following:

![image](https://user-images.githubusercontent.com/3578154/100750212-fbcd5f80-33e5-11eb-9e0f-2ad84c02c2a5.png)

But when clicking the link...

![image](https://user-images.githubusercontent.com/3578154/100750261-0e479900-33e6-11eb-8373-c56fa53aa1d1.png)

**Comment by asvetlov** [comment]
Sorry, CLA was dropped entirely by I cannot delete all CLA comments by a single click.
Please feel free to ignore such comments (or close/hide/delete them -- whatever works better for you).

**Comment by argaen** [comment]
Ahh good, I thought it would appear to all new Pull Requests. Thanks!
