### ISSUE TITLE
Include hashing function parameters and name as a keybuilder

### ISSUE THREAD

**Issue by mateusz-lichota** [aio-libs/aiocache#526]
I faced a scenario where using the string representation of inputs was simply unacceptable, and had to copy the hashing keybuilder from cachetools. I think it would be a great idea to include it as aiocache.key_builders.hash_function_call so that it is readily available for people to use. Let me know if this feature would be desirable, and I'll get to work on a PR

**Comment by argaen** [comment]
Hi @veerte! I'm not sure what's the feature request so if you could provide an example so I get an idea that would be nice

**Comment by veerte** [comment]
If a function takes a large object as an argument, for example a numpy array, converting it to string (as the currently implemented keybuilder does) can take a lot of time or result in unobvious errors (as it happened for me, with scipy.sparse matrices). In other cache libraries it is common to use a hash of all the arguments to save time and space (storing one hash value instad of the whole object as a key).

Currently building a key is done similarily to that:
`def stringify_function_call(func, args, kwargs):
    ordered_kwargs = sorted(kwargs.items())
    return (
        (func.__module__ or "")
        + func.__name__
        + str(args)
        + str(ordered_kwargs)
    )`

My proposed alternative is using something similar to this:
`def hash_function_call(func, *args, **kwargs):
    """Return a cache key for the specified hashable arguments."""
    tup = ((func.__module__ or ""), func.__name__, args)
    if kwargs:
        tup += sum(sorted(kwargs.items()), ())
    
    try:
        return hash(tup)
    except TypeError:
        return hash(pickle.dumps(tup))`
