### ISSUE TITLE
Does this library mitigate dog-piling problem?

### ISSUE THREAD

**Issue by MasterSergius** [aio-libs/aiocache#527]
Here's details - https://en.wikipedia.org/wiki/Cache_stampede
and here's an alternative library https://pypi.org/project/py-memoize/
So, my question: can I use aiocache as a single cache for my async application?

**Comment by argaen** [comment]
https://aiocache.readthedocs.io/en/latest/locking.html#redlock should help. If you find any issues feel free to report or better, contribute :)

**Comment by MasterSergius** [comment]
Thank you for the reply, I'm investigating different solutions and libraries. I need some for my library - [CacheControl for aiohttp](https://github.com/MasterSergius/acachecontrol)
