### ISSUE TITLE
__call__ Method of cached called before decorated method is called

### ISSUE THREAD

**Issue by danygielow** [aio-libs/aiocache#530]
Hi, thank you for this library.

I have a problem with testing functions decorated with `@cached` or `@cached_stampede` with alias.
The __call__ Method of the decorator is called before calling the method itself. That's why I can't use fixtures to set the cache config.

The following test should be OK . But the __call__ function is called while defining the function.
Am I doing something wrong?

```python
# Using pytest, aiocache and pytest-asyncio
import pytest
from aiocache import cached
from aiocache import caches


@pytest.fixture(scope="session", autouse=True)
def default_cache():
    caches.set_config({
        'default': {
            'cache': "aiocache.SimpleMemoryCache",
            'serializer': {
                'class': "aiocache.serializers.StringSerializer"
            }
        },
        'foo': {
            'cache': "aiocache.SimpleMemoryCache",
            'serializer': {
                'class': "aiocache.serializers.StringSerializer"
            }
        }
    })


@cached(alias="foo")
async def cached_function():
    return "bar"


@pytest.mark.asyncio
async def test_cached():
    assert await cached_function() == "bar"

```

**Comment by hmvp** [comment]
That is by design how decorators in python work. Move the function declaration including the `@cached` decorator into you test function and it should work
