### ISSUE TITLE
One dict for any SimpleMemoryBackend instances. Why is that?

### ISSUE THREAD

**Issue by AntonBezdenezhnykh** [aio-libs/aiocache#531]
Hello, I'm trying to use several memory caches for different functions. And I found that SimpleMemoryBackend uses only one dict for all instances. I'm curious why is that? What are underwater stones there?
It looks easy to start using separate dicts for each SimpleMemoryBackend instance.

**Comment by and-semakin** [comment]
Agree. This behavior is a little bit confusing, especially in tests when you receive some unexpected data in the cache that was put there by a previous test. It becomes difficult to write tests that do some assertions about cache.
