### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by zware** [aio-libs/aiocache#536]
There are a few useful changes that are [not available in the latest 0.11.1 release](https://github.com/aio-libs/aiocache/compare/0.11.1...master), such as #478 (fixing Redis `clear` with namespace that happens to be empty), #470 (quieter imports), #514 (explicit support for Python 3.9).

I couldn't find documentation of release plans, so I figured I would just ask here :)

Thanks!

**Comment by amatai** [comment]
Also interested to know about this plan. We are having to fork and use our own `master` branch for the redis clear fix.
Will be very helpful to have a new release.
Willing to help in this effort.

**Comment by Mark90** [comment]
@Dreamsorcerer Should the Github CI build upon the tox/Makefile setup, or doesn't matter how it does the job as long as it lints tests and deploys?

**Comment by Dreamsorcerer** [comment]
Doesn't need tox, just use a version matrix like in the other projects.

**Comment by citramon** [comment]
@Dreamsorcerer, could you check [572](https://github.com/aio-libs/aiocache/pull/572)? It's for the last checkbox :)

**Comment by nikolaevigor** [comment]
so is this project dead?

**Comment by Dreamsorcerer** [comment]
Tests are running again, except for #585. If anyone has time to debug that one, that would be great. I'll continue on with the other tasks on the list for now, and start looking at all the open PRs.

**Comment by Dreamsorcerer** [comment]
OK, I think as we sort out typing, aiojobs and other recent issues, it looks like there will need to be some significant changes to the design.

So, I'll push a release as soon as we have Python 3.11 sorted. The tests on 3.11 are failing, seemingly with the caches not retrieving values: #618.

**Comment by Dreamsorcerer** [comment]
Right, looks like we've got 3.11 working (thanks @a68366). I'll look at doing a release on Friday.

If there's any more PRs people want merged, now is the time. There are quite a few reasonable looking PRs that people haven't bothered to add tests to. So, if anyone wants to finish up any of those, that'd be great.

**Comment by Dreamsorcerer** [comment]
OK, finally out.

If anyone wants to contribute to the next major release, I've tagged several things to do under the 1.0 milestone which are likely to result in backwards-incompatible changes.
https://github.com/aio-libs/aiocache/milestone/8

**Comment by pshafer-als** [comment]
@Dreamsorcerer  Thank you for driving all these updates and getting them released.
