### ISSUE TITLE
Question: How do I use my default config from caches.set_config in the cached decorator?

### ISSUE THREAD

**Issue by paul-rchds** [aio-libs/aiocache#541]
Hi, hope its okay if I ask a question here.

I am not sure how I can use the config I define with caches.set_config({....}) when I using the cached decorator. What I am doing for now is defining a separate config object which I use as the parameters for cached so I don't have to repeat them each time I decorate a function. But it feels like I am missing something?

```
CACHE_SETTINGS = dict(
    ttl=10,
    cache=Cache.REDIS,
    key="key",
    serializer=PickleSerializer(),
    endpoint='redis',
    port=6379,
    namespace="main"
)

@cached(**CACHE_SETTINGS)
async def find(query: str, language: str):
    ....
```

**Comment by Dreamsorcerer** [comment]
Appears to be unsupported currently. I suspect the next major release will also get rid of the config anyway.
