### ISSUE TITLE
redis doesn't work after aioredis package was updated

### ISSUE THREAD

**Issue by citramon** [aio-libs/aiocache#543]
Hi! 
We have a problem after new version [aioredis](https://github.com/aio-libs/aioredis-py/releases/tag/v2.0.0) was released.

```
AttributeError: module 'aioredis' has no attribute 'create_pool'
  File "my_project/apps/checks/services.py", line 66, in my_function
    if await self.cache.exists('key'):
  File "aiocache/base.py", line 61, in _enabled
    return await func(*args, **kwargs)
  File "aiocache/base.py", line 45, in _timeout
    return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
  File "asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "aiocache/base.py", line 75, in _plugins
    ret = await func(self, *args, **kwargs)
  File "aiocache/base.py", line 354, in exists
    ret = await self._exists(ns_key, _conn=_conn)
  File "aiocache/backends/redis.py", line 19, in wrapper
    pool = await self._get_pool()
  File "aiocache/backends/redis.py", line 219, in _get_pool
    self._pool = await aioredis.create_pool((self.endpoint, self.port), **kwargs)
```

**Comment by AlekseiMarinichenko** [comment]
@citramon Use 

```
aiocache
aioredis>=1.3,<2.0
```
in your **requirements.txt** as a temporary fix.

aiocache is unmaintained and I do not think that someone will update it in a near feature

**Comment by citramon** [comment]
> @citramon Use
> 
> ```
> aiocache
> aioredis>=1.3,<2.0
> ```
> 
> in your **requirements.txt** as a temporary fix.
> 
> aiocache is unmaintained and I do not think that someone will update it in a near feature

yep, i did it. Thanks. But I hope the maintainers will fix this someday :)

**Comment by mattyweb** [comment]
@citramon It doesn't look like this project has maintainers. But it looks like it shouldn't be too difficult to fork to add support for aioredis 2.0. There's new syntax for the pool creation and updating that might do it.

It's a shame that this library isn't getting updated though. I'm not sure how aio-libs works but you'd think they'd be kept in sync with one another. Maybe one of the new aioredis maintainers would be gracious enough to take up ownership of this one too...

**Comment by Krukov** [comment]
Hello, maybe It well be helpful for someone -  I got my own library like aiocache, but with supporting aioredis old and new version https://github.com/Krukov/cashews

**Comment by samuelbailey123** [comment]
I ALSO HAVE THIS ISSUE PLEASE FIX :)
