### ISSUE TITLE
Does aiocache support Redis Cluster?

### ISSUE THREAD

**Issue by xiasanshi** [aio-libs/aiocache#544]
Does aiocache support Redis Cluster?

**Comment by gerardcl** [comment]
hi @xiasanshi, it doesn't since it depends on [aioredis](https://github.com/aio-libs/aioredis-py), which it does not provides support for redis cluster (see readme/docs there).

**Comment by Dreamsorcerer** [comment]
We've migrated to redis now. So, if there's a change needed to add support, someone can contribute to it. If another library is needed, then you can always create a custom backend (and feel free to make a PR to link to your new backend).
