### ISSUE TITLE
Current LICENSE file not being packaged with release

### ISSUE THREAD

**Issue by owenlamont** [aio-libs/aiocache#549]
My reviewer noticed the current LICENSE file wasn't being packaged with the release whilst I was repackaging aiocache for [conda-forge](https://github.com/conda-forge/staged-recipes/pull/16637). The release files contain any older LICENSE.txt file that isn't in sync with the source controlled version.

I also note on the PyPi page aiocache's license isn't appearing in the package metadata either:

![image](https://user-images.githubusercontent.com/12672027/138833454-dd13475a-dbb2-41b7-96ce-06e8bf6b9848.png)

The license file was renamed in [PR 524](https://github.com/aio-libs/aiocache/pull/524).  Not sure if that has broken anything or this has been an issue for longer.

**Comment by Dreamsorcerer** [comment]
Think this is fixed now, reopen if there are still problems with 0.12 (will be pushed on Friday).
