### ISSUE TITLE
SSL/TLS support for redis cache

### ISSUE THREAD

**Issue by jonadaly** [aio-libs/aiocache#550]
The `aioredis` library supports connecting to redis using TLS, and has done since version 0.2.6 (see https://github.com/aio-libs/aioredis-py/blob/master/CHANGELOG.md#026-2016-03-30). 

The `aiocache` implementation of the redis backend, however, does not support TLS - it doesn't use the `ssl` parameter when initialising the pool here: https://github.com/aio-libs/aiocache/blob/master/aiocache/backends/redis.py#L209 

You can see the function signature of create_pool here: https://github.com/moserware/aioredis/blob/master/aioredis/pool.py#L14

```python
@asyncio.coroutine
def create_pool(address, *, db=0, password=None, ssl=None, encoding=None,
                minsize=10, maxsize=10, commands_factory=Redis, loop=None):
    ...
```

Is there a reason `aiocache` does not support TLS as a config option for a redis backend? If not, please could support be added?

**Comment by Dreamsorcerer** [comment]
If anyone wants to open a new PR for the current release (which has migrated to the redis library), we can get this included.

**Comment by cancan101** [comment]
This was the code I used for the new Redis library:
```python
class RedisCacheTLS(RedisCache):
    def __init__(self, serializer=None, **kwargs):
        super().__init__(serializer, **kwargs)
        self.client = redis.Redis(
            host=self.endpoint,
            port=self.port,
            db=self.db,
            password=self.password,
            decode_responses=False,
            socket_connect_timeout=self.create_connection_timeout,
            max_connections=self.pool_max_size,
            ssl=True,
            ssl_cert_reqs=None,
        )
```
I added `ssl_cert_reqs=None` to work on Heroku.

**Comment by cancan101** [comment]
I put up this draft PR: https://github.com/aio-libs/aiocache/pull/691
