### ISSUE TITLE
Redis Connection Pooling Across Decorators

### ISSUE THREAD

**Issue by cancan101** [aio-libs/aiocache#552]
I think the answer to this is no, but if I have multiple functions that are decoratored with `cached` and using the redis backend, will they share the same connection pool? ie if I have `pool_max_size=N` on each of the `M` decorators will there be up to `M*N` connections to my redis server? This is important as various PaaS providers (e.g. Heroku) limit the number of connections to the redis service.

**Comment by Krukov** [comment]
Hello, I could be wrong but as I understand - it's depends
If you using aliases with decorators - it should be one pool per alias. But if you pass redis connections parameters for each decorator you will have connection pool for each decorator 
So I suggest you should use aliases
```python
from aiocache import caches, cached

caches.set_config({
    'redis_alt': {
        'cache': "aiocache.RedisCache",
        'endpoint': "127.0.0.1",
        'port': 6379,
        'timeout': 1,
        'serializer': {
            'class': "aiocache.serializers.PickleSerializer"
        },
        'plugins': [
        ]
    }
})

@cached(ttl=10, key="key", alias="redis_alt")
async def cached_call():
    print("Sleeping for three seconds zzzz.....")
    await asyncio.sleep(3)
    return Result("content", 200)

```

Another suggestion with ads - use my library https://github.com/Krukov/cashews - like aiocache, but with batteries

**Comment by Dreamsorcerer** [comment]
This should become irrelevant once #609 is solved. You'll likely need to pass a cache instance to the decorator explicitly.
