### ISSUE TITLE
aiomcache 0.7.0 breaks aiocache[memcached]

### ISSUE THREAD

**Issue by minorgod** [aio-libs/aiocache#554]
New release 0.7.0 of aiomcache breaks aiocache[memcached]. 

https://github.com/aio-libs/aiocache/blob/9c8b07fe759990dcb2d4d5f4e40d13d2cc36d58f/setup.py#L43

Version range probably needs to be changed to something like:
aiomcache>=0.5.2,< 0.7.0

**Comment by minorgod** [comment]
Also, FYI,  I assume this is not related to the Python version, but this was discovered while running in Python 3.8 Docker image. Haven't tested in Python 3.9, but restricting the aiomcache package to version to < 0.7.0 does fix the issue for me in Python 3.8.

**Comment by Dreamsorcerer** [comment]
Working fine in master now, shouldn't be a problem in 0.12.
