### ISSUE TITLE
Cache expiration callback/event

### ISSUE THREAD

**Issue by jmmaa** [aio-libs/aiocache#556]
Is it possible to implement cache expiration events on this lib? If it is can I have an example?

**Comment by Dreamsorcerer** [comment]
Do you mean a callback when a cached item expires?

If so, I think that would depend entirely on the backend. e.g. The `SimpleMemoryBackend` just schedules a function call later. So, by subclassing it, you could figure out a way to get a notification. But, if you use a memcached backend, then the expiration happens in memcached, so you'd need to figure out a way to get the information from there.
