### ISSUE TITLE
Connection <RedisConnection [db:0]> has pending commands, closing it.

### ISSUE THREAD

**Issue by Arzemn** [aio-libs/aiocache#574]
I am getting a d redis bug/issue that i am hoping is not a bug but more in the way i am handling things

this is with aiohttp and aiocache

 i am moving our application to a higher level of concurrency..

The issue i am running into is if add simply aiosync.run(func(input)) i get the following error for any touched coroutine with the @cache() setting

Connection <RedisConnection [db:0]> has pending commands, closing it.
Couldn't retrieve data_dict_2408_1, unexpected error

I have tried to overcome this with a wrapper function that gets the cache manually with the cache.get("key") and if not then fallback to the base function  but as soon the ttl  expires the above error shows up again

**Comment by Dreamsorcerer** [comment]
Please reopen if still an issue on master/0.12. Also provide an actual example, as it's not clear to me where the issue lies.

Possibly related to #609 though.
