### ISSUE TITLE
get cache key for decorated functions with object arguments

### ISSUE THREAD

**Issue by jmmaa** [aio-libs/aiocache#575]
How to get the cache key if I have a cached function like this?
```py
@cached(ttl=30, serializer=PickleSerializer())
async def fetchrow_from_db(pool: asyncpg.Pool, id: int):

    record = await pool.fetchrow("SELECT * FROM my_table WHERE id = $1", id)
    return record


async def get_cache(pool: asyncpg.Pool, id: int):
    record = await fetchrow_from_db.cache.get(...) # how to get in here?
```

**Comment by Dreamsorcerer** [comment]
What's the use case for this?

Why not just do `await fetchrow_from_db(pool, id)`? That'll obviously get the result from the cache.

**Comment by jmmaa** [comment]
> What's the use case for this?
> 
> Why not just do `await fetchrow_from_db(pool, id)`? That'll obviously get the result from the cache.

Actually, I went in a deep rabbit hole onto this one.

First, I really wanted a flexible way of invalidating cache in a simple, functional way in my discord bot. Turns out  that invalidating cache in an atomic way is way too complex.

So yeah I just made my own cache class which is a singleton that I can reuse it in other parts of my bot

**Comment by Dreamsorcerer** [comment]
Right, for invalidating the cache, #625 might be of interest to you.
