### ISSUE TITLE
cache  function difference params

### ISSUE THREAD

**Issue by skriser** [aio-libs/aiocache#628]
for a function,when give difference params, cache differece data.
example:
```
import asyncio

from collections import namedtuple

from aiocache import cached, Cache
from aiocache.serializers import JsonSerializer
# With this we can store python objects in backends like Redis!

Result = namedtuple('Result', "content, status")


@cached(ttl=10, key="key", params=['id'], serializer=JsonSerializer(), namespace="main")
async def cached_call(id=None):
    print("Sleeping for three seconds zzzz.....")
    await asyncio.sleep(3)
    return Result("content", id)


async def run():
    print(await cached_call(1))
    print(await cached_call(1))
    print(await cached_call(1))
    print(await cached_call(4))
    print(await cached_call(1))
    cache = Cache()
    await cache.delete("key")

if __name__ == "__main__":
    asyncio.run(run())
```
i wan response:

```
Sleeping for three seconds zzzz.....
Result(content='content', status=1)
Result(content='content', status=1)
Result(content='content', status=1)
Sleeping for three seconds zzzz.....
Result(content='content', status=4)
Result(content='content', status=1)
```

**Comment by Dreamsorcerer** [comment]
Remove `key=`.

Not sure what the point of this option is, but you are caching all results with the same key.

**Comment by Dreamsorcerer** [comment]
>     :param key: str value to set as key for the function return. Takes precedence over
>        key_builder param. If key and key_builder are not passed, it will use module_name
>        + function_name + args + kwargs

You clearly want the default behaviour.

**Comment by Dreamsorcerer** [comment]
OK, looking in the examples, it seems the `key` is designed to be used on functions which likely take no arguments, so all calls are the same. With the custom key allowing for easy access to the item from the cache.

I think we should probably just remove this argument, as it's easy (and clearer if you've made a mistake) to do `key_builder=lambda _: "key"`.
