### ISSUE TITLE
Ensure that underlying value of enum key is used by BaseCache._build_key() across Python versions

### ISSUE THREAD

**Issue by pshafer-als** [aio-libs/aiocache#633]
Key builders and tests currently cast key values (notably `Enum` values) to `str` to maintain compatibility with Python 3.11 and older versions.  ~~This requirement can be eliminated by using f-strings rather than `str.__format__`.~~

EDIT: Whoops, that erroneous statement was based on testing in the wrong python environment.  Instead of using `str()`, perhaps we should use a simple guard that check for an enum key.  Something like:

```
def ensure_key(key):
    if isinstance(key, Enum):
        return key.value
    else:
        return key
```

**Comment by Dreamsorcerer** [comment]
Is there any issue with using `str()` currently? Seems fine to me.

**Comment by pshafer-als** [comment]
> Is there any issue with using `str()` currently? Seems fine to me.

The result of using str() with an enum is the _name_ of the enum, rather than its _value_.  Earlier versions of `_build_key()` used `"{}".format(key)` which always returned the value of an enum key until Python 3.11 came along.

My impression was that str() is a workaround and that you were trying to get back to earlier functionality. One benefit should be that existing caches would not get invalidated due to key values changing. I might have misunderstood that though.

```
>>> from enum import Enum
>>> from aiocache.base import ensure_key

>>> class Keys(str, Enum):
...    KEY: str = "key"
...    KEY_1: str = "random"

>>> # Option 1
>>> Keys.KEY
<Keys.KEY: 'key'>

>>> # Option 2
>>> str(Keys.KEY))
'Keys.KEY'

>>> # Option 3
>>> "{}".format(Keys.KEY))
'Keys.KEY'  # 3.11
'key'       # 3.7 -- 3.11

>>> # Option 4
>>> ensure_key(Keys.KEY))
'key'
```

In resolving the ambiguity of Option 3, the current implementation of `_build_key()` was switched to Option 2.  I'm proposing to use Option 4 instead, to maintain backward compatibility.

**Comment by Dreamsorcerer** [comment]
I missed that it was the value, actually. Thought the difference was whether it was namespaced or not. Seems reasonable then.
