### ISSUE TITLE
Clarify documentation of `keys_from_attr` and `key_builder` parameters for initializing `multi_cached` decorator

### ISSUE THREAD

**Issue by pshafer-als** [aio-libs/aiocache#636]
Docstring for decorator class `multi_cached` could better explain the use of `keys_from_attr`, `key_builder`, their interaction, and the expected mapping scheme of the dictionary returned by the decorated callable.  Usage is not readily apparent from the current verbiage.

Specifically, documentation should clarify that:

1. In the dictionary returned by the callable, the top level keys should be mappable to a list of values that are provided to a single argument to that callable.
2. The name of that argument should be passed to `keys_from_attr` when `multi_cached` is initialized.
3. If a mapping is needed from input keys (`keys_from_attr`) to the output keys, then `key_builder` should be provided when `multi_cached` is initialized.

A PR will be submitted shortly.

**Comment by Dreamsorcerer** [comment]
You can just create PRs without issues for something like this. ;)
