### ISSUE TITLE
How do I hook up a ttl expiry event?

### ISSUE THREAD

**Issue by 239144498** [aio-libs/aiocache#638]
Hi author, thanks a lot for the python library you made, it's been a great help to me. In the process of using it, I have checked the aiocache documentation in detail and I didn't find anything in BasePlugin that provides an event to handle after ttl expires, and pre_expire is triggered only as an active call to the expire function, but I need to be able to call back after ttl expires, can you provide a minimal demo? Thanks in advance for any help you can provide.

**Comment by Dreamsorcerer** [comment]
It appears there is a `pre_*` and `post_*` for each command. So, just replace "pre" with "post" in your demo.

**Comment by 239144498** [comment]
This is a minimum code demonstration, ask how you can implement the ttl after the callback. I inherit `pre_expire` and `post_expire` but they are invalid. What should I do, please?

    import asyncio
    from aiocache import Cache
    from aiocache.plugins import BasePlugin
    
    
    class MyCustomPlugin(BasePlugin):

        # What function should be inherited here to implement the callback after the ttl expires?

        async def post_expire(self, *args, **kwargs):
            print("post_expire", args, kwargs)
    
        async def pre_expire(self, *args, **kwargs):
            print("pre_expire", args, kwargs)
    
    
    cache = Cache(
        Cache.MEMORY,
        plugins=[MyCustomPlugin()],
        namespace="main")
    
    
    async def demo():
        await cache.set("a", 1, ttl=1)  # Set to expire after 1 second
        await asyncio.sleep(1)
        print(await cache.get("a"))  # Return None, do not get the ttl expiration callback, how do I get the ttl expiration callback in MyCustomPlugin?
        print(await cache.expire("a", 1))  # MyCustomPlugin's pre_expire function is triggered only by active invocation
    
    
    def main():
        asyncio.run(demo())
    
    
    if __name__ == '__main__':
        main()

**Comment by Dreamsorcerer** [comment]
Ah, sorry, looking again those plugin methods are only for commands get(), set() etc.

There doesn't appear to be any method to get triggered on expiry. It's probably difficult to implement as well, as you'd need to figure out how to do something with redis/memcached too.

**Comment by 239144498** [comment]
Well, I tried other ways to achieve it.

**Comment by 239144498** [comment]
Please add new unknown parameters to the base.py file, I'd like to add callback functions to the custom classes, thanks!
```
@API.register
@API.aiocache_enabled(fake_return=True)
@API.timeout
@API.plugins
async def set(
    self, key, value, ttl=SENTINEL, dumps_fn=None, namespace=None, _cas_token=None, _conn=None
):
```

```
@API.register
@API.aiocache_enabled(fake_return=True)
@API.timeout
@API.plugins
async def set(
    self, key, value, ttl=SENTINEL, dumps_fn=None, namespace=None, _cas_token=None, _conn=None, **kwargs
):
```
