### ISSUE TITLE
How do I get the callback event after the ttl parameter has expired?

### ISSUE THREAD

**Issue by 239144498** [aio-libs/aiocache#640]
This is a minimal code demo, how can I implement the callback after ttl expires please. I have inherited `pre_expire` and `post_expire` but it is not working. What do I need to do please?

    import asyncio
    from aiocache import Cache
    from aiocache.plugins import BasePlugin
    
    
    class MyCustomPlugin(BasePlugin):

        # What function should be inherited here to implement the callback after the ttl expires?

        async def post_expire(self, *args, **kwargs):
            print("post_expire", args, kwargs)
    
        async def pre_expire(self, *args, **kwargs):
            print("pre_expire", args, kwargs)
    
    
    cache = Cache(
        Cache.MEMORY,
        plugins=[MyCustomPlugin()],
        namespace="main")
    
    
    async def demo():
        await cache.set("a", 1, ttl=1)  # Set to expire after 1 second
        await asyncio.sleep(1)
        print(await cache.get("a"))  # Return None, do not get the ttl expiration callback, how do I get the ttl expiration callback in MyCustomPlugin?
        print(await cache.expire("a", 1))  # MyCustomPlugin's pre_expire function is triggered only by active invocation
    
    
    def main():
        asyncio.run(demo())
    
    
    if __name__ == '__main__':
        main()

**Comment by Dreamsorcerer** [comment]
Don't open duplicate issues please.
