### ISSUE TITLE
Tests folder being imported when installing version 0.12.0

### ISSUE THREAD

**Issue by tomsoliver** [aio-libs/aiocache#681]
When importing aiocache, it is adding it's tests folder to the virtual env. This is overriding tests in any python solution. For example, the solution:

- src
  - my_module.py
- tests
  - test_my_module.py
  - test_helpers.py

when importing test_helpers from test_my_module:

```python
from tests.test_helpers import helper
```

The aiocache tests module is resolved, not the tests in the solution.

**Comment by Dreamsorcerer** [comment]
You mean when installing aiocache, it installs the tests as a module?

If so, would be great if you can test installing with the change in #682.
