### ISSUE TITLE
Make it possible to run tests with a subset of dependencies

### ISSUE THREAD

**Issue by mgorny** [aio-libs/aiocache#724]
Currently most of the tests seem to be unconditionally import one or more backends, effectively making it impossible to run the test suite without all of the optional dependencies installed. Would you accept a patch to make all of the backends optional in tests, and have pytest skip the respective tests when the dependencies of a specific backend are not available?

**Comment by Dreamsorcerer** [comment]
If it's simple, sure. I think it might be possible to just modify this fixture in some way: https://github.com/aio-libs/aiocache/blob/master/tests/acceptance/conftest.py#L43

**Comment by mgorny** [comment]
Thanks. It's not trivial but it isn't very complex either. I've made #725 for initial discussion of the approach.

**Comment by mgorny** [comment]
Could you make a new release including my changes, please?

**Comment by Dreamsorcerer** [comment]
Sorry for the delay, pushed now.

**Comment by mgorny** [comment]
Thanks a lot! I can confirm that it works now for us in Gentoo.
