### ISSUE TITLE
Preserve function signature with decorator

### ISSUE THREAD

**Issue by Wyko** [aio-libs/aiocache#791]
I've noticed that my IDE (VS Code) does not show the function arguments of anything decorated by the `@cached` decorator. It would be great if the decorator would fully preserve the function's signature.

![image](https://github.com/aio-libs/aiocache/assets/467094/098b9c0e-da43-4130-8a05-ff3c8929f9ba)

**Comment by Dreamsorcerer** [comment]
#512

**Comment by Wyko** [comment]
Does #512 really match the question? Talking about typing vs preserving the original function signature.

**Comment by Dreamsorcerer** [comment]
You're showing type annotations from your IDE. We don't have complete type annotations (or any exposed at all), so your IDE won't give you the correct types.
