### ISSUE TITLE
 Unsupported operand type(s) for +: 'float' and 'SimpleMemoryCache'

### ISSUE THREAD

**Issue by ludsrill** [aio-libs/aiocache#797]
I'm having the following problem when using the @cached decorator, I think the error appears when trying to add a key that already exists to the cache.

Couldn't set {object} in key {key}, unexpected error
Traceback (most recent call last):
  File "/nix/store/.../lib/python3.11/site-packages/aiocache/decorators.py", line 164, in set_in_cache
    await self.cache.set(key, value, ttl=self.ttl)
  File "/nix/store/.../lib/python3.11/site-packages/aiocache/base.py", line 64, in _enabled
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/.../lib/python3.11/site-packages/aiocache/base.py", line 48, in _timeout
    return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/.../lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/nix/store/.../lib/python3.11/site-packages/aiocache/base.py", line 78, in _plugins
    ret = await func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/.../lib/python3.11/site-packages/aiocache/base.py", line 276, in set
    res = await self._set(
          ^^^^^^^^^^^^^^^^
  File "/nix/store/.../lib/python3.11/site-packages/aiocache/backends/memory.py", line 38, in _set
    self._handlers[key] = loop.call_later(ttl, self.__delete, key)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/.../lib/python3.11/asyncio/base_events.py", line 727, in call_later
    timer = self.call_at(self.time() + delay, callback, *args,
                         ~~~~~~~~~~~~^~~~~~~
TypeError: unsupported operand type(s) for +: 'float' and 'SimpleMemoryCache'

**Comment by Dreamsorcerer** [comment]
Some code to reproduce would help. With no context, it looks like you've managed to set ttl to a SimpleMemoryCache.

**Comment by ludsrill** [comment]
``` 
# this would work like asyncio.gather for execute all the methods
# each method call will make requests using run_boto3_fun
for finding, finding_methods in CHECKS:
      if finding not in finding_checks:
          continue
      log_blocking("info", "Executing %s methods", finding.name)
      vulnerabilities = [method(credentials) for method in finding_methods]

      # this would work like asyncio.gather for execute all the methods
      # each method call will make requests using run_boto3_fun
      results += list(
          collapse(
              await collect(vulnerabilities, workers=CPU_CORES),
              base_type=Vulnerability,
          )
      )
```

```
# here is the method that going to use the decorator

def custom_key_builder(_func: Any, *args: Any, **kwargs: Any) -> str:
    input_data = (args, kwargs)
    input_json = json.dumps(input_data, sort_keys=True)
    hash_generator = hashlib.sha256()
    hash_generator.update(input_json.encode("utf-8"))
    hash_value = hash_generator.hexdigest()
    custom_key = f"{hash_value}"
    return custom_key


@aiocache.cached(
    aiocache.SimpleMemoryCache(serializer=MsgPackSerializer()),
    key_builder=custom_key_builder,
)
async def run_boto3_fun(
    credentials: AwsCredentials,
    service: str,
    function: str,
    parameters: dict[str, object] | None = None,
    accepted_error_codes: set[str] | None = None,
) -> dict[str, dict | list]:
    try:
        session = aioboto3.Session(
            aws_access_key_id=credentials.access_key_id,
            aws_secret_access_key=credentials.secret_access_key,
            aws_session_token=credentials.session_token,
        )
        async with session.client(service) as client:
            return await getattr(client, function)(**(parameters or {}))
    except botocore.exceptions.ClientError as error:
            return {}
```

**Comment by Dreamsorcerer** [comment]
> @aiocache.cached(
>     aiocache.SimpleMemoryCache(serializer=MsgPackSerializer()),
>     key_builder=custom_key_builder,
> )

As I said, you're passing a SimpleMemoryCache as the ttl argument. The examples/documentation all say to use kwargs to configure the decorator. This will likely be tightened up to disallow positional arguments in v1.
