### ISSUE TITLE
Caching mutable function outputs

### ISSUE THREAD

**Issue by ludsrill** [aio-libs/aiocache#842]
I have a question with the following
```
@aiocache.cached(
    serializer=PickleSerializer(),
    key_builder=custom_key_builder,
)
async def run_function(
    data: str,
    data_2: str,
) -> list[dict[str, Any]]:
```

Is the cache returning the same reference of the output?,  since the cache can be modified in other scopes this could lead to unexpected bugs

Should I use frozen instances instead of mutable ones, or the cache is immutable by default?

**Comment by Dreamsorcerer** [comment]
I suspect you'd want to avoid mutable objects, but I'm sure you can trivially test the behaviour yourself:
```
l = await run_function(...)
l.append(1)
print(await run_function(...))
```

**Comment by Dreamsorcerer** [comment]
I suspect it ultimately depends on the backend used though, as you're not updating the cache when you append to the list. So, a memory cache might be modifying that object, while a Redis backend would get a new object everytime, or something along those lines...

**Comment by ludsrill** [comment]
It seems that the cached data is not being modified directly when I append to 'L', since I don't want to update the cached once I already got a result, I think I won't get unexpected behavior.
