### ISSUE TITLE
Release v0.13.0?

### ISSUE THREAD

**Issue by mikeoconnor0308** [aio-libs/aiocache#942]
The v0.12 release is quite far behind main.

Specifically, for my purposes, it doesn't not include the fix (https://github.com/aio-libs/aiocache/commit/5007dc25278877a47b94a4dbe43a4afec27951ac)  for https://github.com/aio-libs/aiocache/issues/563, the multi_cached key mutation issue. 

I'm also aware that it's a breaking change, so either needs to be a v0.13.0 release with a note or a v1.0.0 release. 

It's quite confusing for users for the released package to be so far behind, so I'd advocate for a v0.13.0 release if possible. 

Are there any blockers to that?

**Comment by Dreamsorcerer** [comment]
Yes, as you just said, it's backwards incompatible. Compatible changes have been cherry-picked to 0.12 branch.
If you want to see v1 happen sooner, then feel free to work on the issues in the milestone (they are in order of what needs to be done first).
